### ISSUE TITLE
VertexBuffer resource barriers not working correctly

### ISSUE THREAD

**Issue by FireFlyForLife** [jpvanoosten/LearningDirectX12#1] opened 2018-09-15 12:33 UTC
This was noticed when creating a DebugRenderer which uploads a vertex buffer of lines every frame and then renders it.

**Comment by jpvanoosten** [comment] 2018-09-15 12:59
Can you please provide a test case (in a fork of this repo) that reproduces the issue?

**Comment by FireFlyForLife** [comment] 2018-09-15 14:54
Yes ofcourse! this I my fork: https://github.com/FireFlyForLife/LearningDirectX12

I modified the Tutorial project, in Tutorial3.h I added the DebugRenderer object:
https://github.com/FireFlyForLife/LearningDirectX12/blob/master/Tutorial3/inc/Tutorial3.h#L94

And in Tutorial3.cpp I added the Initialize call and add some example lines:
https://github.com/FireFlyForLife/LearningDirectX12/blob/master/Tutorial3/src/Tutorial3.cpp#L121-L123

And finally try to render the debug overlay in the onRender() function:
https://github.com/FireFlyForLife/LearningDirectX12/blob/master/Tutorial3/src/Tutorial3.cpp#L585

Thank you for your time!
~Maiko

**Comment by FireFlyForLife** [comment] 2018-09-17 10:10
After a while debugging I found the issue.

At `CommandList::CopyVertexBuffer(...)` and then `CommandList::CopyBuffer(...)` the global state of the vertex buffer resource was set to `D3D12_RESOURCE_STATE_COMMON` while it was in the state `D3D12_RESOURCE_STATE_COPY_DEST`. at the end of the method I added a this line: `
	ResourceStateTracker::AddGlobalResourceState(d3d12Resource.Get(), D3D12_RESOURCE_STATE_COPY_DEST);`

Then, the difference between Tutorial 3 and my debug renderer is that you load the mesh vertex buffers in `LoadContent()` where you execute the command list. However I load the vertex buffer and try to draw it in the same list. This is a problem because `ID3D12GraphicsCommandList2::Draw(...)` will already check if the vertex buffer resource is in the correct state, however, because the VertexBuffer resource was already used to copy stuff to, the state is already known which means that now the resource barrier is placed in `m_PendingResourceBarriers` and the pending resource barriers will only be flushes when the `CommandlList::Close()` is called (when the command queue is executed). So what I had to do was create a new method `CommandList::ForceFlushPendingResourceBarriers()` to make sure that the resource barriers were correctly pushed to the command list, since Draw() only calls `FlushResourceBarriers()` which only looks at the `m_ResourceBarriers` which the new barriers were not placed on.

I have pushed my solution to my fork in this commit: https://github.com/FireFlyForLife/LearningDirectX12/commit/2047c20dfad84cfb844027c35dfe58dbc408095f

**Comment by jpvanoosten** [comment] 2018-09-27 12:50
I've fixed this by explicitly transitioning the ID3D12Resource to D3D12_RESOURCE_STATE_COPY_DEST before updating the subresource of the buffer. 

The resource was not being transitioned explicitly to the COPY_DEST state because I was relying on "Common state promotion" as described in this article: [Using Resource Barriers to Synchronize Resource States in Direct3D 12](https://docs.microsoft.com/en-us/windows/desktop/direct3d12/using-resource-barriers-to-synchronize-resource-states-in-direct3d-12#common-state-promotion). 

The fix has been pushed in jpvanoosten/LearningDirectX12@0669f4aa5411913d9df8a6e3a578bbb1e7167906.

**Closed by jpvanoosten** 2018-09-27 12:50 UTC
